//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.04 at 10:28:41 AM UTC 
//


package com.spring.training.model;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.spring.training.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.spring.training.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMatieresRequest }
     * 
     */
    public GetMatieresRequest createGetMatieresRequest() {
        return new GetMatieresRequest();
    }

    /**
     * Create an instance of {@link GetMatieresResponse }
     * 
     */
    public GetMatieresResponse createGetMatieresResponse() {
        return new GetMatieresResponse();
    }

    /**
     * Create an instance of {@link Matiere }
     * 
     */
    public Matiere createMatiere() {
        return new Matiere();
    }

    /**
     * Create an instance of {@link GetMatiereRequest }
     * 
     */
    public GetMatiereRequest createGetMatiereRequest() {
        return new GetMatiereRequest();
    }

    /**
     * Create an instance of {@link GetMatiereResponse }
     * 
     */
    public GetMatiereResponse createGetMatiereResponse() {
        return new GetMatiereResponse();
    }

    /**
     * Create an instance of {@link CreateMatiereRequest }
     * 
     */
    public CreateMatiereRequest createCreateMatiereRequest() {
        return new CreateMatiereRequest();
    }

    /**
     * Create an instance of {@link CreateMatiereResponse }
     * 
     */
    public CreateMatiereResponse createCreateMatiereResponse() {
        return new CreateMatiereResponse();
    }

    /**
     * Create an instance of {@link UpdateMatiereRequest }
     * 
     */
    public UpdateMatiereRequest createUpdateMatiereRequest() {
        return new UpdateMatiereRequest();
    }

    /**
     * Create an instance of {@link UpdateMatiereResponse }
     * 
     */
    public UpdateMatiereResponse createUpdateMatiereResponse() {
        return new UpdateMatiereResponse();
    }

    /**
     * Create an instance of {@link DeleteMatiereRequest }
     * 
     */
    public DeleteMatiereRequest createDeleteMatiereRequest() {
        return new DeleteMatiereRequest();
    }

    /**
     * Create an instance of {@link DeleteMatiereResponse }
     * 
     */
    public DeleteMatiereResponse createDeleteMatiereResponse() {
        return new DeleteMatiereResponse();
    }

}
