//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.04 at 10:28:41 AM UTC 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://spring.com/training/model", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.spring.training.model;
