spring:
  application:
    name: discovery-service
  cloud:
    config:
      enabled: false
eureka:
  client:
    #don't register itself as client
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
  server:
    enable-self-preservation: true
#logging:
#  level:
#    com.netflix.eureka : DEBUG
server:
  port: 8761

